config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
	resources :prt_folios, except: [:show]
	get 'prt_folio/:id', to: 'prt_folios#show', as: 'prt_folio_show'
  get 'angular-item', to: 'prt_folios#angular'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs  do
    member do
      get :toggle_status
    end
  end
  root to: 'pages#home'
	
  # get 'pages/home'
  # get 'pages/about'
  # get 'pages/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_application_footer.html.erb
<footer class="mastfoot mt-auto">
  <div class="inner">
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_application_nav.html.erb
<header class="masthead">
  <div class="inner">
    <h3 class="masthead-brand">Sandeep Soni </h3>
    <nav class="nav nav-masthead justify-content-center app-nav">
      <%= nav_helper("nav-link","span") %>
      <%= login_helper('nav-link') %>
    </nav>
  </div>
</header>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p><%= copyright_generator %></p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header" style="margin-bottom: 2rem;">
  <div class="container">
    <h1 class="blog-title">My blog</h1>
    <p class="lead blog-description">An example blog template buit with bootstrap</p>
    <%= link_to 'New Blog', new_blog_path if logged_in?(:site_admin) %>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary" style="margin-bottom: 3rem;">
  <div class="collapse navbar-collapse container">
    <div class="navbar-nav">
      <%= nav_helper("nav-link","span") %>
      <%= login_helper('nav-link') %>
    </div>
  </div>
</nav>

app/views/shared/_blog_sidebar.html.erb
<aside class="col-md-4 blog-sidebar">
  <div class="p-3 mb-3 bg-light rounded">
    <h4 class="font-italic">About</h4>
    <p class="mb-0">Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Archives</h4>
    <ol class="list-unstyled mb-0">
      <li><a href="#">March 2014</a></li>
      <li><a href="#">February 2014</a></li>
      <li><a href="#">January 2014</a></li>
      <li><a href="#">December 2013</a></li>
      <li><a href="#">November 2013</a></li>
      <li><a href="#">October 2013</a></li>
      <li><a href="#">September 2013</a></li>
      <li><a href="#">August 2013</a></li>
      <li><a href="#">July 2013</a></li>
      <li><a href="#">June 2013</a></li>
      <li><a href="#">May 2013</a></li>
      <li><a href="#">April 2013</a></li>
    </ol>
  </div>

  <div class="p-3">
    <h4 class="font-italic">Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="#"><%= fa_icon("github") %></a></li>
      <li><a href="#"><%= fa_icon("twitter") %></a></li>
      <li><a href="#"><%= fa_icon("facebook") %></a></li>
      <li><a href="#"><%= fa_icon("instagram") %></a></li>
    </ol>
  </div>
</aside>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blogs", blogs_path%></div>
  <div><%= link_to "Portfolio", prt_folios_path%></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
    	<%= link_to "View all portfolios", prt_folios_path %> / 
      <a href="#">Back to top</a>
    </p>
    <p><%= copyright_generator %></p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1>My portfolio</h1>
    <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
    <p>
      <%= link_to "Find out more about me", about_me_path,class: "btn btn-primary my-2" %>
      <%= link_to "My blog", blogs_path,class: "btn btn-secondary my-2" %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header>
  <div class="collapse bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4 class="text-white">About</h4>
          <p class="text-muted">With over a year of development experience in a hospitality industry I realized that the typical product creation process between clients and developers was flawed.All to often developers rarely communicate with clients throughout the development stage, resulting in a final product that fails to reach the goal sought by customer and end user.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4 class="text-white">Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper("text-white","li") %>
            <li><%= login_helper("text-white") %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container d-flex justify-content-between">
      <a href="#" class="navbar-brand d-flex align-items-center">
        <strong>Sancoder</strong>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>