config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register'}
	resources :prt_folios, except: [:show]
	get 'prt_folio/:id', to: 'prt_folios#show', as: 'prt_folio_show'
  get 'angular-item', to: 'prt_folios#angular'

  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs  do
    member do
      get :toggle_status
    end
  end
  root to: 'pages#home'
	
  # get 'pages/home'
  # get 'pages/about'
  # get 'pages/contact'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/prt_folio.rb
class PrtFolio < ApplicationRecord
	has_many :technologies
	accepts_nested_attributes_for :technologies,
																reject_if: lambda {|attr| attr['name'].blank? }
	
	include Placeholder
	validates_presence_of :title, :body

	def self.angular
		where(subtitle: "Angular")
	end

	scope :ruby_on_rails_portfolio_itmes, -> { where(subtitle: "Ruby on Rails")}

	after_initialize :set_defaults

	def set_defaults
		self.main_image ||= Placeholder.image_genegator(height: 600, width: 400)
		self.thumb_image ||= Placeholder.image_genegator(height: 350, width: 200)
	end
end

app/controllers/prt_folios_controller.rb
class PrtFoliosController < ApplicationController
  layout 'prt_folio'
  before_action :set_portfolio_item, only: [:show, :edit, :update, :destroy]
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :edit, :update]}, site_admin: :all
	def index
		@portfolio_items = PrtFolio.all
	end

  def angular
    @angular_portfolio_item = PrtFolio.angular
  end

	def new	
		@portfolio_item = PrtFolio.new
    3.times { @portfolio_item.technologies.build }
	end

	def create
    @portfolio_item = PrtFolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to prt_folios_path, notice: 'Your portfolio  is live now' }
      else
        format.html { render :new }
      end
    end
  end

  def edit     
  end

  def update
     
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to prt_folios_path, notice: 'The record successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show    
  end

  def destroy
    @portfolio_item.destroy
    respond_to do |format|
      format.html { redirect_to prt_folios_path, notice: 'The record successfully destroyed.' }
    end
  end

  private

  def portfolio_params
    params.require(:prt_folio).permit(:title,  :subtitle, :body,
                                      technologies_attributes: [:name])
  end

  def set_portfolio_item
    @portfolio_item = PrtFolio.find(params[:id])
  end
end

app/helpers/prt_folios_helper.rb
module PrtFoliosHelper
end

app/views/prt_folios/_form.html.erb
<%= form_for(portfolio_item) do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title,class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle,class: "form-control" %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body,class: "form-control", rows: 12 %>
      </div> 
    </div>
  </div>
  <hr>
  <div class="col-md-12">
    <h2>Technologies used: </h2>
    <div>
      <%= f.fields_for :technologies do |technology_form | %>
        <div class="form-group">
          <%= technology_form.label :name %>
          <%= technology_form.text_field :name,class: "form-control" %>
        </div>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.submit "Save portfolio item", class: "btn btn-primary btn-block" %>
    </div>
  </div>
<% end %>

app/views/prt_folios/_portfolio_item.html.erb
<!-- <p></p>
<p></p>
<p></p>
<%= image_tag portfolio_item.thumb_image  unless portfolio_item.thumb_image.nil? %>
<%= link_to("Edit", edit_prt_folio_path(portfolio_item)) if logged_in?(:site_admin) %>
<%= link_to("Delete", portfolio_item, method: :delete, data: {confirm: 'Are you sure?'}) if logged_in?(:site_admin) %> -->


<div class="col-md-4">
  <div class="card mb-4 shadow-sm">
    <%= image_tag portfolio_item.thumb_image  unless portfolio_item.thumb_image.nil? %>
    <div class="card-body">
      <p class="card-text">
      	<span><%= link_to(portfolio_item.title, prt_folio_show_path(portfolio_item))  %></span>
      	<%= portfolio_item.subtitle %>  	
      </p>
      <!-- <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
          <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
        </div>
        <small class="text-muted">9 mins</small>
      </div> -->
    </div>
  </div>
</div>

app/views/prt_folios/angular.html.erb
<h1>Angular Portfolio Items</h1>

<%= link_to("Create New Item", new_prt_folio_path) %>

<% @angular_portfolio_item.each do |portfolio_item| %>
	<p><%= link_to(portfolio_item.title, prt_folio_show_path(portfolio_item))  %></p>
	<p><%= portfolio_item.subtitle %></p>
	<p><%= portfolio_item.body %></p>
	<%= image_tag portfolio_item.thumb_image  unless portfolio_item.thumb_image.nil? %>
	<%= link_to("Edit", edit_prt_folio_path(portfolio_item)) if logged_in?(:site_admin) %>
	<%= link_to("Delete", portfolio_item, method: :delete, data: {confirm: 'Are you sure?'}) if logged_in?(:site_admin) %>
<% end %>

app/views/prt_folios/edit.html.erb
<div class="container portfolio-form">
	<h1>Edit this portfolio item</h1>

	<%= render "form", portfolio_item: @portfolio_item %>
</div>

app/views/prt_folios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
  	<div class="row">
			<%= render partial:  'portfolio_item', collection: @portfolio_items %>
		</div>
	</div>
</div>

app/views/prt_folios/new.html.erb
<div class="container portfolio-form">
	<h1>Create a new portfolio item</h1>

	<%= render "form", portfolio_item: @portfolio_item %>
</div>

app/views/prt_folios/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-7">
			<%= image_tag(@portfolio_item.main_image) %>
		</div>
		<div class="col-md-5">
			<h1><%= @portfolio_item.title %></h1>

			<em><%= @portfolio_item.subtitle %></em>

			<p><%= @portfolio_item.body %></p>

			<h3>Technologies Used:</h3>

			<% @portfolio_item.technologies.each do |t| %>
				<p><%= t.name %></p>
			<% end %>	
		</div>
	</div>
</div>